# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = var.aws_region
  allowed_account_ids = ["987654321012"]

  # Make it faster by skipping something
  skip_get_ec2_platforms      = true
  skip_metadata_api_check     = true // commented when using with iam_role on ec2
  skip_region_validation      = true
  skip_credentials_validation = true
}

variable "aws_region" {
  description = "AWS region to create infrastructure in"
  type        = string
  default     = "us-east-1"
}
